defmodule AoD.Release do
  @moduledoc """
  Mix release steps for the dual-mode `aod` binary.

  The `aod` binary needs to behave two ways:

    * As a Phoenix server (`./aod start`, used by `mix aod.up` inside
      a sprite) — invoked the same way any Mix release binary is.
    * As the operator-side CLI (`./aod conv list`, `./aod run agent
      -p "..."`, etc.) — this is what the escript at
      `lib/aod_cli.ex` does today, except the escript needs a host
      Erlang install. The Burrito-wrapped binary doesn't.

  We achieve both modes with a tiny shell dispatcher that wraps the
  release's autogenerated `bin/aod`. Standard release subcommands
  (`start`, `daemon`, `eval`, `rpc`, ...) are forwarded as-is;
  anything else is dispatched into `AodCli.main/1` via `eval`.

  Args are embedded into the eval expression as a literal Elixir list
  so we don't have to wrestle with how the release script forwards
  argv into eval'd code.
  """

  @release_subcommands ~w(
    start start_iex daemon daemon_iex stop restart pid version
    rpc rpcterms eval remote
    install reload migrate console console_clean console_boot
  )

  @doc """
  Mix release step. Renames the autogenerated `bin/aod` to
  `bin/aod-release` and writes a new `bin/aod` dispatcher.
  """
  def dual_mode_dispatcher(%Mix.Release{path: path} = release) do
    bin_dir = Path.join(path, "bin")
    original = Path.join(bin_dir, "aod")
    relocated = Path.join(bin_dir, "aod-release")

    File.rename!(original, relocated)
    File.chmod!(relocated, 0o755)

    File.write!(original, dispatcher_script())
    File.chmod!(original, 0o755)

    # Mix release also writes bin/<name>.bat for Windows. We don't
    # ship a Windows target, but be tidy if it's there.
    bat = Path.join(bin_dir, "aod.bat")
    if File.exists?(bat), do: File.rm!(bat)

    release
  end

  @doc false
  def dispatcher_script do
    subcommands = Enum.join(@release_subcommands, "|")

    # `~S` so backslashes and quotes inside the shell script aren't
    # mangled by Elixir's escape processing. The single placeholder
    # gets substituted after.
    template = ~S"""
    #!/bin/sh
    # Auto-generated by AoD.Release.dual_mode_dispatcher/1.
    # Forwards standard Mix release subcommands to bin/aod-release;
    # anything else is dispatched to AodCli.main/1 via `eval`.
    set -e

    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    RELEASE_BIN="$SCRIPT_DIR/aod-release"

    case "${1:-}" in
      ""|__SUBCOMMANDS__)
        exec "$RELEASE_BIN" "$@"
        ;;
      *)
        # Build an Elixir list literal of args, escaping each element
        # for embedding in an Elixir double-quoted string. Then eval
        # AodCli.main([...]) — embedding into the expression sidesteps
        # the question of how `eval` would otherwise forward argv.
        args=""
        for arg in "$@"; do
          esc=$(printf '%s' "$arg" | sed 's/\\/\\\\/g; s/"/\\"/g')
          if [ -z "$args" ]; then
            args="\"$esc\""
          else
            args="$args, \"$esc\""
          fi
        done
        exec "$RELEASE_BIN" eval "AodCli.main([$args])"
        ;;
    esac
    """

    String.replace(template, "__SUBCOMMANDS__", subcommands)
  end
end
